### ISSUE TITLE
feeback / comments

### ISSUE THREAD

**Issue by vinyar** [ericmaxwell/Awesome-Appliance-Repair-Cookbook#2]
I would suggestion combining all case statements into one location, in the attribute file for example

So instead of having a `case` statement in default and apache recipe, you can have a single case statement in the attribute file

``` ruby
case node['platform_family']
when 'debian'
  default['awesome-applicalce-repair-coobook']['package_update_command'] = 'apt-get update'
  default['awesome-applicalce-repair-coobook']['apache_service_name'] = 'apache2'
  default['awesome-applicalce-repair-coobook']['script_to_run'] = 'AARinstall.py'
when 'rhel'
  default['awesome-applicalce-repair-coobook']['package_update_command'] = 'yum -y update'
  default['awesome-applicalce-repair-coobook']['apache_service_name'] = 'httpd'
  default['awesome-applicalce-repair-coobook']['script_to_run'] = 'AARinstall-rhel.py'
else
  raise "Platform not supported... exiting!"
end
```

A couple of other minor suggestions (maybe personal preference):
- I would suggest trying to keep github repo and cookbook name in line as much as possible. 
- I would avoid recasting variables `platform_fam = node['platform_family']` as you can just use `node['platform_family']` directly
- There is a chef link resource for creating symlinks https://docs.chef.io/resource_link.html
- Instead of `node.default['awesome_appliance']['mysql_root_pass']` attributes can be referenced with shorthand `node['awesome_appliance']['mysql_root_pass']`
- Instead of `execute unzip` you can leverage one of the community 'unzip' cookbooks, like `tar`, `ark` or 7zip.
- You can use `file` resource to chmod a file to a specific set of permissions.

**Comment by vinyar** [comment]
oh yea, also run `foodcritic` and `rubocop` against the cookbook for additional feedback :+1: 
execute `foodcritic .` or `rubocop` (without params) in the cookbook directory.

**Comment by iameirikr** [comment]
I've applied virtually all these suggested changes, thanks!
